<?php
switch ( $textpart ) {
	//branches.php, branchmenu.php
	case "branches":
		$admtext['branchlabel'] = "Branch Label";
		$admtext['existingbranch'] = "Existing Branch";
		$admtext['newbranch'] = "New Branch";
		$admtext['startingind'] = "Starting Individual";
		$admtext['numgenerations'] = "Number of Generations";
		$admtext['ancestors'] = "Ancestors";
		$admtext['descofanc'] = "Descendant generations from each ancestor";
		$admtext['descendants'] = "Descendants";
		$admtext['includespouses'] = "Include spouses of descendants";
		$admtext['partial'] = "Partial";
		$admtext['addlabels'] = "Add labels";
		$admtext['clearlabels'] = "Clear labels";
		$admtext['clearingbranch'] = "Clearing Branch Labels";
		$admtext['addingbranch'] = "Adding Branch Labels";
		$admtext['totalaffected'] = "Total Affected";
		$admtext['labelmore'] = "Label more branches";
		$admtext['enterbranch'] = "Please select an existing branch or enter a new one.";
		$admtext['enterstartingind'] = "Please enter a starting individual ID.";
		$admtext['gensnumeric'] = "Values for Ancestors and Descendants must be numeric.";
		//changed in 5.0.0
		$admtext['overwrite'] = "Overwrite";
		$admtext['branchid'] = "Branch ID";
		$admtext['addnewbranch'] = "Add New Branch";
		$admtext['createbranch'] = "Create a record for a new branch";
		$admtext['existingbranchinfo'] = "Existing Branch Information";
		$admtext['editexistingbranch'] = "Edit information for a previously entered branch";
		$admtext['confbranchdelete'] = "Are you sure you want to delete this branch?";
		$admtext['enterbranchid'] = "Please enter a branch ID.";
		$admtext['entertreedesc'] = "Please enter a branch description.";
		$admtext['newbranchinfo'] = "New Branch Information";
		$admtext['modifybranch'] = "Edit Existing Branch";
		$admtext['changestobranch'] = "Changes to branch";
		$admtext['existlabels'] = "Existing labels";
		$admtext['leave'] = "Leave";
		$admtext['append'] = "Append New";
		$admtext['showpeople'] = "Show people with this tree/branch";
		//added in 6.0.0
		$admtext['branchdiscl'] = "This number represents the total number of branch links, not necessarily the number of people or families currently linked to this branch. If you have recently re-imported your data, you may need to relabel your branches.";
		//added in 7.0.0
		$admtext['inclspouses'] = "Include spouses for all descendants";
		$admtext['delpeople'] = "Delete people and families with this branch label";
		$admtext['confbrdel'] = "Are you sure you want to delete all people and families with this branch label?";
		break;
		
	//addcemetery.php, updatecemetery.php, findcemetery.php, cemeteries.php, editcemetery.php, newcemetery.php
	case "cemeteries":
		$admtext['mapnotcopied'] = "The map image file could not be copied to";
		$admtext['changestocem'] = "Changes to cemetery";
		$admtext['modifycemetery'] = "Edit Existing Cemetery";
		$admtext['addnewcemetery'] = "Add New Cemetery";
		$admtext['createnewcemetery'] = "Create a record for a new cemetery";
		$admtext['selectcemaction'] = "Select Cemetery and Action";
		$admtext['cemeterymenu'] = "Cemeteries Menu";
		$admtext['location'] = "Location";
		$admtext['confdeletecem'] = "Are you sure you want to delete this cemetery?";
		$admtext['editceminfo'] = "Edit information for a previously entered cemetery";
		$admtext['leaveblankallcems'] = "leave blank to show all cemeteries";
		$admtext['cemeteryname'] = "Cemetery Name";
		$admtext['mapfilename'] = "Map File Name";
		$admtext['countyparish'] = "County/Parish";
		$admtext['stateprovince'] = "State/Province/Shire";
		$admtext['entercountry'] = "Please enter a country name.";
		$admtext['entermapfile'] = "Please enter a file name for your map file on the web server.";
		$admtext['existingceminfo'] = "Existing Cemetery Information";
		$admtext['newceminfo'] = "New Cemetery Information";
		$admtext['maptoupload'] = "Map image to upload";
		$admtext['mapfilenamefolder'] = "Map File Name<br/>within Headstones folder";
		$admtext['ifmapuploaded'] = "Leave this field blank if the file has already been uploaded to your headstones folder.";
		//changed in 6.0.0
		$admtext['requiredmap'] = "Required if you are using a map. This should correspond to the name and location of your file <em>within the headstones folder</em> once the file is uploaded. For example, if your headstones folder is called <em>headstones</em>,	and you want your file to be called <em>map.jpg</em> and go in a subfolder of headstones called <em>mymaps</em>, you would enter <em>mymaps/map.jpg</em> in this field.";
		break;
	
	//addentity.php, newentity.php
	case "entities":
		$admtext['alreadyexists'] = "already exists";
		$admtext['added'] = "Added";
		$admtext['enternew'] = "Enter new";
		$admtext['pleaseenter'] = "Please enter a ";
		$admtext['netscapereload'] = "Netscape users: <br/>You must reload the Cemeteries page to see your new";
		break;
		
	//addnote.php, deletenote.php, updatenote.php, newnote.php
	case "notes":
		$admtext['deletingnote'] = "Deleting Note...";
		$admtext['addingnote'] = "Adding Note...";
		$admtext['addnewnote'] = "Add New Note";
		$admtext['note'] = "Note";
		$admtext['modifynote'] = "Modify Note";
		$admtext['text_private'] = "Private";
		break;

	//addevent.php, deleteevent.php, updateevent.php, editevent.php, newevent.php
	case "events":
		$admtext['addingevent'] = "Adding Event...";
		$admtext['deletingevent'] = "Deleting Event...";
		$admtext['updatingevent'] = "Updating Event...";
		$admtext['modifyevent'] = "Modify Event";
		$admtext['addnewevent'] = "Add New Event";

		$admtext['dateformat'] = "(DD MMM YYYY)";
		$admtext['age'] = "Age";
		$admtext['agency'] = "Agency";
		$admtext['cause'] = "Cause";
		$admtext['moreinfo'] = "More Information";
		break;

	//gedimport.php
	case "gedimport":
		$admtext['importinggedcom'] = "Importing GEDCOM...<br/>(this may take several minutes)";
		$admtext['ifimportfails'] = "If the import fails to run to completion,";
		$admtext['resume'] = "click here to resume";
		$admtext['opened'] = "opened...";
		$admtext['toresume'] = "to resume import";  //cannot open to resume import
		$admtext['openedtoresume'] = "opened to resume import...";
		$admtext['notresumed'] = "Import could not be resumed.";
		$admtext['finishedimporting'] = "Finished Importing GEDCOM";
		$admtext['treeexists'] = "New tree name already exists";
		$admtext['backtodataimport'] = "Back to Data Import";
		//no break here is intentional to allow import scripts to have access to eventtypes messages
	//addeventtype.php, updateeventtype.php, eventtypes.php, neweventtype.php, editeventtype.php
	case "eventtypes":
		$admtext['changestoevtype'] = "Changes to event type";
		$admtext['modifyeventtype'] = "Edit Existing Event Type";
		$admtext['individual'] = "Individual";
		$admtext['entertypedesc'] = "Please enter a type/description for this new event type.";
		$admtext['enterdisplay'] = "Please enter a display string for this new event type.";
		$admtext['eventtypesmenu'] = "Event Types Menu";
		$admtext['existingeventtypeinfo'] = "Existing Event Type Information";
		$admtext['neweventtypeinfo'] = "New Event Type Information";
		$admtext['tag'] = "Tag";
		$admtext['typedescription'] = "Type/Description";
		$admtext['onimport'] = "On Import";
		$admtext['accept'] = "Accept";
		$admtext['ignore'] = "Ignore";
		$admtext['typerequired'] = "With custom tags (where tag = \"EVEN\"), this is the TYPE and is required. Optional for all other tags.";
		$admtext['addnewevtype'] = "Add New Event Type";
		$admtext['createnewevtype'] = "Create a new event type record";
		$admtext['forindividuals'] = "For Individuals...";
		$admtext['forfamilies'] = "For Families...";
		$admtext['existingevtypes'] = "Existing Event Types";
		$admtext['edsevtypes'] = "Edit, delete or sort previously entered event types";
		$admtext['indfam'] = "Ind/Fam";  //individual family
		$admtext['confdeleteevtype'] = "Are you sure you want to delete this event type?";
		$admtext['selecttag'] = "Select Tag";
		$admtext['selectentertag'] = "Please select or enter the tag for this event type.";
		$admtext['orenter'] = "or enter";
		$admtext['ifbothdata'] = "will take precedence if both fields contain data";
		$admtext['EVEN'] = "Event";
		$admtext['ADOP'] = "Adopted";
		$admtext['ADDR'] = "Address";
		$admtext['ALIA'] = "Also Known As";
		$admtext['ANCI'] = "Submitter";
		$admtext['BARM'] = "Barmitzvah";
		$admtext['BASM'] = "Basmitzvah";
		$admtext['CAST'] = "Caste";
		$admtext['CENS'] = "Census";
		$admtext['CHRA'] = "Adult Christening";
		$admtext['CONF'] = "Confirmation";
		$admtext['CREM'] = "Cremated";
		$admtext['DSCR'] = "Physical Description";
		$admtext['EDUC'] = "Education";
		$admtext['EMIG'] = "Emigration";
		$admtext['FCOM'] = "First Communion";
		$admtext['GRAD'] = "Graduation";
		$admtext['IDNO'] = "National ID Number";
		$admtext['IMMI'] = "Immigration";
		$admtext['LANG'] = "Language";
		$admtext['NATI'] = "Nationality";
		$admtext['NATU'] = "Naturalization";
		$admtext['NCHI'] = "Count of Children";
		$admtext['NMR'] = "Count of Marriages";
		$admtext['OCCU'] = "Occupation";
		$admtext['ORDI'] = "Ordinance";
		$admtext['ORDN'] = "Ordained";
		$admtext['PHON'] = "Phone";
		$admtext['PROB'] = "Probate";
		$admtext['PROP'] = "Possessions";
		$admtext['RELI'] = "Religion";
		$admtext['RESI'] = "Residence";
		$admtext['RESN'] = "Restriction Notice";
		$admtext['RETI'] = "Retired";
		$admtext['RFN'] = "Permanent Record Number";
		$admtext['SSN'] = "Social Security Number";
		$admtext['WILL'] = "Will";
		$admtext['ANUL'] = "Annulled";
		$admtext['DIVF'] = "Divorce Filed";
		$admtext['ENGA'] = "Engaged";
		$admtext['MARB'] = "Marriage Banns";
		$admtext['MARC'] = "Marriage Contract";
		$admtext['MARL'] = "Marriage License";
		$admtext['MARS'] = "Marriage Settlement";
		$admtext['forsources'] = "For Sources...";
		$admtext['RIN'] = "Record ID Number";
		$admtext['REFN'] = "Reference Number";
		$admtext['REPO'] = "Repository";

		$admtext['deleteselected'] = "Delete Selected";
		$admtext['ignoreselected'] = "Ignore Selected";
		$admtext['acceptselected'] = "Accept Selected";
		$admtext['changestoallevtypes'] = "Changes to all event types";
		$admtext['forrepos'] = "For Repositories...";
		$admtext['noevtypes'] = "No event types exist.";
		$admtext['DESI'] = "Descendant Interest";
		//added in 6.0.0
		$admtext['allnone'] = "Enter a display message for each language,<br />or leave all blank and enter one display message above.";
		$admtext['assocwith'] = "Associated with";
		$admtext['BAPM'] = "Baptism";
		$admtext['umps'] = "Your GEDCOM file may be larger than the maximum size allowed by your PHP installation. You can ask your provider to increase the \"upload_max_filesize\" value, or you can copy your file to the \"gedcom\" folder on your site and import it from there instead.;";
		$admtext['othlangs'] = "Other Languages";
		$admtext['evdata'] = "Event Data";
		break;

	//addfamily.php, updatefamily.php, findfamily.php, editfamily.php, newfamily.php
	case "families":
		$admtext['changestofamily'] = "Changes to family";
		$admtext['marrdate'] = "Marr Date"; //marriage date
		$admtext['modifyfamily'] = "Edit Existing Family";
		$admtext['selectfamaction'] = "Select Family and Action";
		$admtext['familymenu'] = "Families Menu";
		$admtext['confdeletefam'] = "Are you sure you want to delete this family?";
		$admtext['existingfamilyinfo'] = "Existing Information for Family";
		$admtext['newfamilyinfo'] = "New Family Information";
		$admtext['sealedsdate'] = "Sealed S Date (LDS)";     //S is for spouse
		$admtext['sealedsplace'] = "Sealed S Place (LDS)";     //S is for spouse
		$admtext['newchildren'] = "New Children";
		$admtext['addnewfamily'] = "Add New Family";
		$admtext['createnewfamily'] = "Create a record for a new family";
		$admtext['editexistingfaminfo'] = "Edit information for a previously entered family";
		$admtext['spousesids'] = "Spouses' IDs";
		$admtext['noname'] = "No Name";
		$admtext['familyidbefevent'] = "You must enter a Family ID before you can add new events.";
		$admtext['prefixfamilyid'] = "Please prefix Family ID with \"F\" for \"Family\"";
		$admtext['enterfamilyid'] = "Please enter a Family ID.";
		$admtext['validfamilyid'] = "Please enter a valid Family ID. A valid ID is a numeric string prefixed with 'F'.";
		$admtext['familyidbefnote'] = "You must enter a Family ID before you can add new notes.";
		$admtext['familyidbefcite'] = "You must enter a Family ID before you can use citations with this family.";

		$admtext['genfamily'] = "General Family";
		$admtext['marriagetype'] = "Marriage Type";
		$admtext['reviewfamilies'] = "Accept or decline tentative changes to families";
		//changed in 7.0.0
		$admtext['fevslater'] = "Note: Children and additional events, plus event-specific notes and citations, may be added on the next screen.";
		$admtext['husbid'] = "Father ID";  //husband ID
		$admtext['wifeid'] = "Mother ID";
		$admtext['enternamepart'] = "Enter part of father's and/or mother's name";
		$admtext['pleasenamepart'] = "Please enter part of the father\'s or mother\'s name.";
		//added in 7.0.0
		$admtext['clickfind'] = "Click Find or Create =>";
		$admtext['chunlinked'] = "Child unlinked from family";
		$admtext['confremchild'] = "Are you sure you want to remove this child from this family? The individual will not be deleted from the database.";
		$admtext['child'] = "Child";
		break;
		
	//addperson.php, addperson2.php, updateperson.php, findperson.php, editperson.php, newperson.php, newperson2.php, people.php, findperson2.php
	case "people":
		$admtext['addingperson'] = "Adding Person...";
		$admtext['changestoperson'] = "Changes to person";
		$admtext['nobirthinfo'] = "No birth info";
		$admtext['modifyperson'] = "Edit Existing Person";
		$admtext['personmenu'] = "People Menu";
		$admtext['selectpersaction'] = "Select Person and Action";
		$admtext['existingpersoninfo'] = "Existing Information for Person";
		$admtext['firstgivennames'] = "First/Given Name(s)";
		$admtext['lastsurname'] = "Last/Surname";
		$admtext['nickname'] = "Nickname";
		$admtext['male'] = "Male";
		$admtext['female'] = "Female";
		$admtext['bapldate'] = "Baptism Date (LDS)";
		$admtext['baplplace'] = "Baptism Place (LDS)";
		$admtext['endldate'] = "Endowment Date (LDS)";
		$admtext['parents'] = "Parents";
		$admtext['father'] = "Father";
		$admtext['mother'] = "Mother";
		$admtext['unlinkindividual'] = "Unlink current individual";
		$admtext['aschild'] = "as child";
		$admtext['sealedpdate'] = "Sealed P Date (LDS)";     //P is for parents
		$admtext['sealedpplace'] = "Sealed P Place (LDS)";     //P is for parents
		$admtext['asspouse'] = "as spouse";
		$admtext['spouse'] = "Spouse";
		$admtext['ordernumber'] = "Order Number";
		$admtext['married'] = "Married";
		$admtext['nonewfamily'] = "Do not go to new family on save";
		$admtext['addnewperson'] = "Add New Person";
		$admtext['createperson'] = "Create a record for a new individual";
		$admtext['personidbefevent'] = "You must enter a Person ID before you can add new events.";
		$admtext['prefixpersonid'] = "Please prefix Person ID with \"I\" for \"Individual\"";
		$admtext['validpersonid'] = "Please enter a valid Person ID. A valid ID is a numeric string prefixed with 'I'.";
		$admtext['newpersoninfo'] = "New Person Information";
		$admtext['selectsex'] = "Please select a gender.";
		$admtext['shortform'] = "Short Form";
		$admtext['editexistingpersoninfo'] = "Edit information for a previously entered individual";
		$admtext['unknown'] = "Unknown";
		$admtext['personidbefnote'] = "You must enter a Person ID before you can add new notes.";
		$admtext['endlplace'] = "Endowment Place (LDS)";
		$admtext['livingonly'] = "Living only";
		$admtext['personidbefcite'] = "You must enter a Person ID before you can use citations with this person.";
		$admtext['relationship'] = "Relationship";
		$admtext['adopted'] = "adopted";
		$admtext['birth'] = "birth";
		$admtext['foster'] = "foster";
		$admtext['sealing'] = "sealing";
		$admtext['asspouse'] = "as spouse";
		$admtext['mergepeople'] = "Merge information for duplicate individual records.";
		$admtext['choosemerge'] = "Choose individuals to merge or find potential matches";
		$admtext['usesoundex'] = "Use Soundex";
		$admtext['sdxdisclaimer'] = "Using this option will cause the program to take longer when finding the next match or duplicate.";
		$admtext['combinenotes'] = "Combine notes &amp; citations";
		$admtext['confirmmerge'] = "Are you sure you want to merge these two individuals?";
		$admtext['gotonewfamily'] = "Go to new family with current individual";

		$admtext['genperson'] = "General Individual";
		$admtext['reviewpeople'] = "Accept or decline tentative changes to individuals";
		//added in 6.0.0
		$admtext['nokids'] = "No children";
		$admtext['noparents'] = "No parents";
		$admtext['association'] = "Association";
		$admtext['confdeleteassoc'] = "Are you sure you want to delete this association?";
		$admtext['deletingassoc'] = "Deleting Association...";
		$admtext['addingassoc'] = "Adding Association...";
		$admtext['updatingassoc'] = "Updating Association...";
		$admtext['addnewassoc'] = "Add New Association";
		$admtext['enterpassoc'] = "Please enter the ID of the associated person.";
		$admtext['enterrela'] = "Please enter the relationship.";
		$admtext['modifyassoc'] = "Edit Existing Association";
		//changed in 7.0.0
		$admtext['pevslater'] = "Note: Additional events, plus event-specific notes and citations, may be added on the next screen.";
		$admtext['ashusband'] = "as father";
		$admtext['aswife'] = "as mother";
		//added in 7.0.0
		$admtext['confunlink'] = "Are you sure you want to unlink this individual as a spouse in this family?";
		$admtext['pevslater2'] = "Note: Additional events, plus event-specific notes and citations, may be added later.";
		$admtext['nospouse'] = "No spouse";
		$admtext['revassoc'] = "Also add reverse association for same two people";
		$admtext['chkdel'] = "Check empty box to delete item at left";
		$admtext['prefix'] = "Prefix";
		//changed in 7.0.1
		$admtext['chkdel'] = "Check empty box to delete item at left";
		break;

	case "headstones":
	case "photos":
		//$admtext['photonotcopied'] = "The photo file could not be copied to";
		$admtext['thumbnailnotcopied'] = "The thumbnail file could not be copied to";
		$admtext['photo'] = "Photo";
		$admtext['changestophoto'] = "Changes to photo";
		$admtext['modifyphoto'] = "Edit Existing Photo";
		$admtext['addnewphoto'] = "Add New Photo";
		$admtext['selectphotoaction'] = "Select Photo and Action";
		$admtext['photomenu'] = "Photos Menu";
		$admtext['photoid'] = "Photo ID";
		$admtext['confdeletephoto'] = "Are you sure you want to delete this photo and all links associated with it?";
		$admtext['enterphotopath'] = "Please enter the path (folder and file name) of the image file within the photos folder on your web server.";
		$admtext['enterthumbnailpath'] = "Please enter the path (folder and file name) of the thumbnail image file within the photos folder on your web server.";
		$admtext['enterphotodesc'] = "Please enter a description for the image.";
		$admtext['existingphotoinfo'] = "Existing Photo Information";
		//$admtext['newphotoinfo'] = "New Photo Information";
		$admtext['thumbnailfile'] = "Thumbnail Image File";
		//$admtext['thumbnailtoupload'] = "Image file to upload";
		$admtext['fileandpath'] = "File and Path Name";
		$admtext['sortphotos'] = "Sort Photos";
		$admtext['sortphotosfor'] = "Sort Photos for";
		$admtext['editexistingphotoinfo'] = "Edit information for a previously entered photo";
		$admtext['leaveblankallphotos'] = "leave blank to show all photos";
		$admtext['headstone'] = "Headstone";
		$admtext['imagenotcopied'] = "The image file could not be copied to";
		$admtext['changestohs'] = "Changes to headstone";
		$admtext['modifyheadstone'] = "Edit Existing Headstone";
		$admtext['selecthsaction'] = "Select Headstone and Action";
		$admtext['headstonemenu'] = "Headstones Menu";
		$admtext['confdeletehs'] = "Are you sure you want to delete this headstone?";
		$admtext['photostatus'] = "Photo/Status";
		$admtext['selectcemetery'] = "Please select a cemetery.";
		$admtext['enterhsimage'] = "Please enter a file name for your headstone image on the web server.";
		$admtext['existinghsinfo'] = "Existing Headstone Information";
		$admtext['newhsinfo'] = "New Headstone Information";
		$admtext['hsimagefile'] = "Headstone Image File";
		$admtext['status'] = "Status";
		$admtext['located'] = "Located";
		$admtext['notyetlocated'] = "Not yet located";
		$admtext['unmarked'] = "Unmarked";
		$admtext['missing'] = "Missing";
		$admtext['cremated'] = "Cremated";
		$admtext['leaveblankhs'] = "Leave this field blank if the file has already been uploaded to your headstones folder.";
		$admtext['requiredhs'] = "Required. This should correspond to the name and location of your file <em>within the headstones folder</em> once the file is uploaded. For example, if your headstones folder is called <em>photos/headstones</em>, and you want your file to be called <em>headstone.jpg</em> and go in a subfolder of photos/headstones called <em>newheadstones</em>, you would enter <em>newheadstones/headstone.jpg</em> in this field.";
		$admtext['addnewhs'] = "Add New Headstone";
		$admtext['createnewhs'] = "Create a record for a new headstone and link it to an individual";
		$admtext['editexistinghsinfo'] = "Edit information for a previously entered headstone";
		$admtext['leaveblankallhs'] = "leave blank to show all headstones";
		$admtext['cemnamelocation'] = "Cemetery Name or Location";
		$admtext['pedphoto'] = "Use this photo on pedigree charts and in name titles";
		$admtext['photoowner'] = "Owner/Source";
		$admtext['show'] = "Preview";
		$admtext['dimensions'] = "Dimensions";
		$admtext['selectphoto'] = "Select Image";
		$admtext['specifyimg'] = "Specify image";
		$admtext['autoimg'] = "Create from original";
		$admtext['enterthumbpath'] = "Please enter a destination name for your thumbnail image";
		$admtext['genthumbs'] = "Generate Thumbnails";
		$admtext['genthumbsdesc'] = "Automatically generate smaller versions of all photos without existing thumbnails.";
		$admtext['thumbsgenerated'] = "Thumbnails generated";
		$admtext['makedefault'] = "Make Default";
		$admtext['filewithinhs'] = "Path within headstones folder <br/>(subfolder and file name)";
		$admtext['recsupdated'] = "Records updated";
		$admtext['removedef'] = "Remove default photo";
		$admtext['numlinkhs'] = "Number of people to link to this headstone";
		$admtext['sortheadstones'] = "Sort Headstones";
		$admtext['sortheadstonesfor'] = "Sort Headstones for";
		$admtext['sortheadstonesind'] = "Sort Headstones for an Individual";
		$admtext['headstoneorder'] = "Indicate a desired order for the headstones linked to a specific individual";
		$admtext['enternumberforphoto'] = "Enter a numeric value for each item.";
		$admtext['updownforphoto'] = "Click the up and down arrows to move items up or down in the order.";
		$admtext['createnewphoto'] = "Create a record for a new photo and link it to individuals, families or sources";
		$admtext['numlinkphoto'] = "Number of people, families or sources to link to this photo";
		$admtext['photoorder'] = "Indicate a desired order for the photos linked to a specific individual, family or source";
		$admtext['assigndefs'] = "Assign Default Photos";
		$admtext['assigndefsdesc'] = "Make first photo for each individual, family and source be that entity's default photo.";
		$admtext['overwritedefs'] = "Overwrite existing defaults";
		$admtext['assign'] = "Assign Defaults";
		$admtext['defsassigned'] = "Default photos assigned";
		//$admtext['isdocument'] = "This image is a document";
		$admtext['imgmap'] = "Image Map";
		$admtext['circle'] = "circle";
		$admtext['rect'] = "rectangle";
		$admtext['poly'] = "polygon";
		$admtext['shape'] = "Shape of region";
		//$admtext['radius'] = "Radius (pixels)";
		$admtext['width'] = "Width (pixels)";
		$admtext['height'] = "Height (pixels)";
		$admtext['imgdim'] = "Image dimensions";
		$admtext['pixw'] = "pixels wide";
		$admtext['pixh'] = "pixels high";
		//$admtext['convtohs'] = "Convert to Headstones";
		//$admtext['convtodoc'] = "Convert to Documents";
		//$admtext['convtophoto'] = "Convert to Photos";
		$admtext['changestoallphotos'] = "Changes to all selected photos";
		$admtext['changestoallhs'] = "Changes to all selected headstones";
		//changed in 6.0.0
		$admtext['datetaken'] = "Date Taken/Created";
		$admtext['placetaken'] = "Place Taken/Created";
		$admtext['abspath'] = "This media comes from an external source (you must supply your own thumbnail)";
		$admtext['imagefile'] = "Media File";
		$admtext['pathwithinphotos'] = "File name on site";
		$admtext['linktocem'] = "Link this media directly to the selected cemetery";
		$admtext['defphotonote'] = "Use the thumbnail to identify this person, family or source on pedigree and other charts, including family group sheets.";
		$admtext['photonotadded'] = "The item could not be added, most likely because another media record already exists for the collection and physical file specified.";
		$admtext['requiredphoto'] = "Required. This should correspond to the name and location of your file <em>within the collection folder</em> once the file is uploaded. For example, suppose you are uploading a photo and your photos folder is called <em>photos</em>. If you want your file to be called <em>myphoto.jpg</em> and go in a subfolder of photos called <em>newphotos</em>, you would enter <em>newphotos/myphoto.jpg</em> in this field.";
		$admtext['leaveblankphoto'] = "Leave this field blank if the file has already been uploaded.";
		$admtext['thumbconflicts'] = "Thumbnails not generated due to path, permissions, size or file name problems";
		$admtext['showmap'] = "Show cemetery map and media whenever this item is displayed";
		//moved here in 6.0.0
		$admtext['bodytext'] = "<strong>OR</strong><br/>Body Text";
		$admtext['usenl'] = "Convert line breaks to HTML on display";
		$admtext['newwin'] = "Open in new window";
		//added in 6.0.0
		$admtext['modifymedia'] = "Edit Existing Media";
		$admtext['addnewmedia'] = "Add New Media";
		$admtext['confdeletemedia'] = "Are you sure you want to delete this media?";
		$admtext['thumbnails'] = "Thumbnails";
		$admtext['modifyalbum'] = "Edit Existing Album";
		$admtext['addnewalbum'] = "Add New Album";
		$admtext['newalbuminfo'] = "New Album Information";
		$admtext['confdeletealbum'] = "Are you sure you want to delete this album?";
		$admtext['enteralbumname'] = "Please enter an album name.";
		$admtext['albumname'] = "Album Name";
		$admtext['keywords'] = "Keywords";
		$admtext['changestoalbum'] = "Changes to album";
		$admtext['addtoalbum'] = "Add to Album";
		$admtext['mediatype'] = "Collection";
		$admtext['fileext'] = "File ext."; //file extension (abbreviation)
		$admtext['anotherlink'] = "Add Another Link";
		$admtext['mediaurl'] = "Media URL";
		$admtext['put_in'] = "Store files in";
		$admtext['usemedia'] = "Multimedia Folder";
		$admtext['usecollect'] = "Collection Folder (e.g., \"photos\")";
		$admtext['notcopied'] = "The file could not be copied to";
		$admtext['existingmediainfo'] = "Existing Media Information";
		$admtext['convto'] = "Convert Selected to";
		$admtext['changestoallmedia'] = "Changes to all selected media";
		$admtext['changestoitem'] = "Changes to item";
		$admtext['eventlink'] = "Link to specific event";
		$admtext['sortmediaind'] = "Sort Media for an Individual, Family, Source, Repository or Place";
		$admtext['sortmedia'] = "Sort xxx for";
		$admtext['unlinked'] = "Unlinked only";
		$admtext['samepaths'] = "The principal image and the thumbnail image may not be the same file. Please select a different thumbnail image, or have one created for you.";
		$admtext['regenerate'] = "Regenerate existing thumbnails";
		$admtext['forcircles'] = "For circles";
		$admtext['forrects'] = "For rectangles";
		$admtext['circleinstr'] = "First click in the center of the circle, then click anywhere on the outside of the circle.";
		$admtext['rectinstr'] = "First click in the upper left corner of the rectangle, then click in the lower right corner.";
		$admtext['firstone'] = "first one";
		$admtext['controller'] = "Please allow about 16 vertical pixels for the media player controller.";
		//added in 6.1.0
		$admtext['nostatus'] = "No status";
		//changed in 7.0.0
		$admtext['enterid'] = "Please enter an ID for the selected Link Type.";
		$admtext['existingalbuminfo'] = "Album Information";
		$admtext['newmediainfo'] = "Media Information";
		$admtext['mapinstr2'] = "Link regions of your image to different people or other pages (optional)";
		$admtext['mapinstr3'] = "To link a region of this photo to a specific individual, select the individual's tree, pick a shape and dimensions for the region, then click the center of that region on the photo. A popup box will help you select the individual. After the selection is made, code for the image map will be added to the box below. Repeat this process as needed for additional regions.";
		//added in 7.0.0
		$admtext['albumlinks'] = "Album Links";
		$admtext['duplinkmsg'] = "A link to the selected entity already exists in this album.";
		$admtext['invlinkmsg'] = "The entity ID you entered is invalid. No link was created.";
		$admtext['albmedia'] = "Album Media";
		$admtext['removelink'] = "Remove Link";
		$admtext['confdellink'] = "Are you sure you want to delete this link?";
		$admtext['confremmedia'] = "Are you sure you want to remove this media from this album?";
		$admtext['selmedia'] = "Search for existing media to include in this album";
		$admtext['uploadfirst'] = "upload new media here first";
		$admtext['existmedia'] = "Existing Media";
		$admtext['emoptions'] = "Browse, Delete or Drag to Sort";
		$admtext['addlinks'] = "Add New Links";
		$admtext['existlinks'] = "Existing Links";
		$admtext['eloptions'] = "Browse or Delete";
		$admtext['inclmsg'] = " included";
		$admtext['mediasubt'] = "Manage media included in this album (Add, Delete, Sort)";
		$admtext['infosubt'] = "Edit album name, description and keywords";
		$admtext['linkssubt'] = "Link this album to People, Families, Sources, Repositories or Places";
		$admtext['inclmedia'] = "Included Media";
		$admtext['nomedia'] = "No media included yet";
		$admtext['nolinks'] = "No links exist yet";
		$admtext['thumbsize'] = "(original is too large)";
		$admtext['thumbinv'] = "(invalid image or inadequate permissions)";
		$admtext['thumblost'] = "(original not found)";
		$admtext['uplsel'] = "Upload a new file from your computer, or select from files already on your site";
		$admtext['alblater'] = "Note: Media may be added to this album, and the album linked to individuals or families, on the next screen.";
		$admtext['medlater'] = "Note: More information may be added, and the item linked to individuals or families, on the next screen.";
		$admtext['minfosubt'] = "Edit media title, description and other basic details";
		$admtext['medialinks'] = "Media Links";
		$admtext['defphoto'] = "Default Photo";
		$admtext['alttd'] = "Alt Title/Desc";   //short abbreviation for "Alternate Title or Description"
		$admtext['editmedialink'] = "Edit Media Link";
		$admtext['plot'] = "Plot";
		$admtext['addnewcoll'] = "Add Collection";
		$admtext['collid'] = "Collection ID";
		$admtext['colldisplay']= "Display Title";
		$admtext['collpath'] = "Folder Name";
		$admtext['collicon'] = "Icon File";
		$admtext['colllike'] = "Same setup as";
		$admtext['entercollid'] = "Please enter a collection ID.";
		$admtext['entercolldisplay'] = "Please enter a collection display name.";
		$admtext['entercollpath'] = "Please enter a collection folder name.";
		$admtext['entercollicon'] = "Please enter a collection icon file name.";
		$admtext['editcoll'] = "Edit Collection";
		$admtext['confmtdelete'] = "Are you sure you want to delete this media type?";
		$admtext['histlimit'] = "<strong>Size note:</strong> Most browsers limit the amount of data that can be sent in a web form to about 64Kb. If you have a large amount of text to type or paste in the Body Text field above, you might consider using historytemplate.php instead. See the Help for more information.";
		$admtext['repath'] = "Regenerate thumbnail path names where file does not exist";
		$admtext['linkedto'] = "Linked to";
		$admtext['sortalbumind'] = "Sort Albums for an Individual, Family, Source, Repository or Place";
		$admtext['cidexists'] = "The Collection ID you entered could not be added because it already exists.";
		break;

	//addreport.php, updatereport.php, newreport.php, editreport.php
	case "reports":
		$admtext['report'] = "Report";
		$admtext['changestoreport'] = "Changes to report";
		$admtext['modifyreport'] = "Edit Existing Report";
		$admtext['reportmenu'] = "Reports Menu";
		$admtext['existingreportinfo'] = "Existing Report Information";
		$admtext['existingreports'] = "Existing Reports";
		$admtext['newreportinfo'] = "New Report Information";
		$admtext['reportname'] = "Report Name";
		$admtext['rankpriority'] = "Rank/Priority";
		$admtext['active'] = "Active";
		$admtext['choosedisplay'] = "Choose Fields to Display";
		$admtext['spouseid'] = "Spouse ID";
		$admtext['spousename'] = "Spouse Name";
		$admtext['lastmodified'] = "Last Modified Date";
		$admtext['ldsbapldate'] = "LDS Baptism Date";
		$admtext['ldsbaplplace'] = "LDS Baptism Place";
		$admtext['ldsendldate'] = "LDS Endowment Date";
		$admtext['ldsendlplace'] = "LDS Endowment Place";
		$admtext['ldssealsdate'] = "LDS Seal/Spouse Date";
		$admtext['ldssealsplace'] = "LDS Seal/Spouse Place";
		$admtext['ldssealpdate'] = "LDS Seal/Parents Date";
		$admtext['ldssealpplace'] = "LDS Seal/Parents Place";
		//$admtext['makelink'] = "Make Link";
		$admtext['choosecriteria'] = "Choose Criteria";
		$admtext['fullname'] = "Full Name";
		$admtext['lastfirst'] = "Last Name, First Name";
		$admtext['monthonlyfrom'] = "Month Only From";
		$admtext['yearonlyfrom'] = "Year Only From";
		$admtext['dayonlyfrom'] = "Day Only From";
		$admtext['operators'] = "Operators";
		$admtext['contains'] = "contains";
		$admtext['startswith'] = "starts with";
		$admtext['endswith'] = "ends with";
		$admtext['text_and'] = "AND";
		$admtext['currentmonth'] = "Current Month";
		$admtext['currentyear'] = "Current Year";
		$admtext['currentday'] = "Current Day";
		$admtext['constantstring'] = "Constant String";
		$admtext['constantvalue'] = "Constant Value";
		$admtext['foremptystring'] = "For an empty string, leave this field blank and click \"Add >>.\"";
		$admtext['choosesort'] = "Choose Sort Fields";
		$admtext['savereport'] = "Save Report";
		$admtext['addnewreport'] = "Add New Report";
		$admtext['createreport'] = "Create a new report";
		$admtext['noreports'] = "No reports exist";
		$admtext['rank'] = "Rank";
		$admtext['confreportdelete'] = "Are you sure you want to delete this report?";
		$admtext['enterreportname'] = "Please enter a Report Name.";
		$admtext['selectdisplayfield'] = "Please select at least one display field.";
		$admtext['today'] = "Today (true date)";
		$admtext['convtodays'] = "Convert to Days";
		$admtext['desc'] = "Descending (Prev)";
		$admtext['birthdatetr'] = "Birth Date (True)";
		$admtext['chrdatetr'] = "Christening Date (True)";
		$admtext['deathdatetr'] = "Death Date (True)";
		$admtext['burialdatetr'] = "Burial Date (True)";
		$admtext['marriagedatetr'] = "Marriage Date (True)";
		$admtext['ldsbapldatetr'] = "LDS Baptism Date (True)";
		$admtext['ldsendldatetr'] = "LDS Endowment Date (True)";
		$admtext['ldssealsdatetr'] = "LDS Seal/Spouse Date (True)";
		$admtext['ldssealpdatetr'] = "LDS Seal/Parents Date (True)";
		$admtext['currentmonthnum'] = "Current Month Number";
		$admtext['livingtrue'] = "Living = yes";
		$admtext['livingfalse'] = "Living = no";
		$admtext['altreport'] = "OR Leave Display, Criteria and Sort fields blank and enter direct SQL SELECT statement here";
		$admtext['rptdate'] = "Date";
		$admtext['rptdatetr'] = "Date (True)";
		$admtext['fact'] = "Fact";
		//changed in 6.0.0
		$admtext['testeditdelete'] = "Add, edit, test or delete reports";
		//added in 6.0.0
		$admtext['whatsnew'] = "What's New";
		$admtext['wnmsg'] = "Message on \"What's New\" Page";
		//added in 7.0.0
		$admtext['mwtype'] = "Type";
		$admtext['mysphoto'] = "Mystery Photos";
		$admtext['mysperson'] = "Elusive People";
		$admtext['selphoto'] = "Select Photo";
		$admtext['entertitle'] = "Please enter a title";
		$admtext['enterdesc'] = "Please enter a description";
		$admtext['confremmw'] = "Are you sure you want to remove this item?";
		//added in 7.0.1
		$admtext['msgsaved'] = "Message saved";
		break;

	//index.php
	case "index":
		$admtext['selectimportfile'] = "Please select a file to import.";
		$admtext['importgedcom'] = "Import GEDCOM (standard 5.5 format)";
		$admtext['addreplacedata'] = "Add to or replace your genealogy (may take several minutes, depending on the size of your file)";
		$admtext['fromyourcomputer'] = "From your computer";
		$admtext['importdata'] = "Import Data";
		$admtext['setupfirsttime'] = "Set up the software for the first time.";
		$admtext['replace'] = "Replace (in selected tree)";
		$admtext['desttree'] = "Destination Tree";
		$admtext['selectdesttree'] = "Please select or enter a destination tree.";
		$admtext['selectexisting'] = "Import into";
		$admtext['importgedcom2'] = "Import a GEDCOM file";
		$admtext['setupitems'] = "Create database tables, Set preferences";
		$admtext['custeventitems'] = "Manage custom tags and event types";
		$admtext['usersitems'] = "Manage users and permissions";
		$admtext['reportsitems'] = "Create custom lists and reports";
		$admtext['langitems'] = "Manage alternate languages";
		$admtext['backupitems'] = "Back up, restore and optimize database tables";
		$admtext['ucaselast'] = "Upper case all surnames";
		$admtext['norecalc'] = "Do not recalculate Living flag";
		$admtext['autooffset'] = "Start IDs at first available number";

		$admtext['mustselecttree'] = "You must select a tree before choosing this option.";
		$admtext['showlog'] = "Change Log";
		$admtext['importmedia'] = "Import media if present";
		$admtext['mainmenu'] = "Main Menu";
		$admtext['neweronly'] = "Replace only if newer";
		$admtext['secondaryitems'] = "Create a GENDEX file, Track lines of descent";
		//changed in 6.0.0
		$admtext['onwebserver'] = "From web site (in GEDCOM folder)";
		//added in 6.0.0
		$admtext['eventsonly'] = "Import Custom Event Types only (no data is added, replaced or appended)";
		$admtext['imphints'] = "Hints: All Current Data means all people, families, sources and notes (media associations are not lost as long as IDs remain the same). Matches are always based on IDs only. New records are always added. Append imports all records with new IDs.";
		//added in 7.0.0
		$admtext['allevents'] = "Accept data for all new Custom Event Types";
		$admtext['destbranch'] = "Destination Branch (optional)";
		$admtext['inframe'] = "(in frame)";
		$admtext['getstart'] = "Getting Started";
		$admtext['importlatlong'] = "Import latitude / longitude data if present";
		break;

	//addsource.php, updatesource.php, newsource.php, editsource.php, sources.php
	case "sources":
		$admtext['changestosource'] = "Changes to source";
		$admtext['modifysource'] = "Edit Existing Source";
		$admtext['selectsrcaction'] = "Select Source and Action";
		$admtext['sourcemenu'] = "Sources Menu";
		$admtext['sourceid'] = "Source ID";
		$admtext['shorttitle'] = "Short Title";
		$admtext['longtitle'] = "Long Title";
		$admtext['author'] = "Author";
		$admtext['callnumber'] = "Call Number";
		$admtext['publisher'] = "Publisher";
		$admtext['actualtext'] = "Actual Text";
		$admtext['confdeletesrc'] = "Are you sure you want to delete this source?";
		$admtext['selectshorttitle'] = "Please select or enter a short title for this event type.";
		$admtext['existingsourceinfo'] = "Existing Information for Source";
		$admtext['newsourceinfo'] = "New Source Information";
		$admtext['addnewsource'] = "Add New Source";
		$admtext['prefixsourceid'] = "Please prefix Source ID with \"S\" for \"Source\"";
		$admtext['entersourceid'] = "Please enter a Source ID.";
		$admtext['validsourceid'] = "Please enter a valid Source ID. A valid ID is a numeric string prefixed with 'S'.";
		$admtext['createsource'] = "Create a record for a new source";
		$admtext['editexistingsource'] = "Edit information for a previously entered source";
		$admtext['addnewcite'] = "Add New Citation";
		$admtext['reliability'] = "Reliability";
		$admtext['relyexplain'] = "Higher numbers indicate greater reliability.";
		$admtext['citedate'] = "Citation Date";
		$admtext['modifycite'] = "Edit Existing Citation";
		$admtext['addingcite'] = "Adding Citation...";
		$admtext['deletingcite'] = "Deleting Citation...";
		$admtext['updatingcite'] = "Updating Citation...";

		$admtext['citation'] = "Citation";
		$admtext['sevslater'] = "Note: Additional events and notes may be added after the new source has been saved.";
		$admtext['pleasesourcepart'] = "Please enter part of the source title.";
		$admtext['addnewrepo'] = "Add New Repository";
		$admtext['modifyrepo'] = "Edit Existing Repository";
		$admtext['createrepo'] = "Create a record for a new repository";
		$admtext['editexistingrepo'] = "Edit information for a previously entered repository";
		$admtext['repoid'] = "Repository ID";
		$admtext['enterrepoid'] = "Please enter a Repository ID.";
		$admtext['enterreponame'] = "Please enter a Repository name.";
		$admtext['newrepoinfo'] = "New Repository Information";
		$admtext['prefixrepoid'] = "Please prefix Repository ID with \"REPO\" for \"Repository\"";
		$admtext['selectrepoaction'] = "Select Repository and Action";
		$admtext['confdeleterepo'] = "Are you sure you want to delete this repository?";
		$admtext['changestorepo'] = "Changes to repository";
		$admtext['existingrepoinfo'] = "Existing Information for Repository";
		//added in 6.0.0
		$admtext['pleaserepopart'] = "Please enter part of the repository title.";
		$admtext['choosemergesources'] = "Choose sources to merge or find potential matches";
		$admtext['confirmmergesources'] = "Are you sure you want to merge these two sources?";
		$admtext['choosemergerepos'] = "Choose repositories to merge or find potential matches";
		$admtext['confirmmergerepos'] = "Are you sure you want to merge these two repositories?";
		$admtext['revslater'] = "Note: Additional events and notes may be added after the new repository has been saved.";
		//added in 7.0.0
		$admtext['confdeleterepo'] = "Are you sure you want to delete this repository?";
		break;

	//checkID.php
	case "checkID":
		$admtext['checknewid'] = "Check New ID";
		$admtext['checking'] = "Checking...Please wait";
		$admtext['idnotvalid'] = "is not a valid ID. A valid ID is a numeric string prefixed with";
		$admtext['idinuse'] = "is in use. Please choose a different ID";
		$admtext['idok'] = "is OK to use";
		break;
	
	//setup.php
	//editconfig.php, backuprestore.php
	case "setup":
		$admtext['tablesuccess'] = "Tables created successfully.";
		$admtext['backtosetup'] = "Back to the Setup Menu";
		$admtext['configuration'] = "Configuration";
		$admtext['entersysvars'] = "Enter values for system variables.";
		$admtext['createdbtables'] = "Create the database tables to hold your information.";
		$admtext['tcwarning'] = "<strong>Warning!</strong> Select this option only when you are setting your site up for the first time. <strong>All existing data, including photos, histories, headstones and cemetery information, will be erased!</strong>";
		$admtext['conftabledelete'] = "This will delete ALL your existing data!! Are you sure you want to continue?";
		$admtext['performdatamaint'] = "Perform data maintenance and manage photos, histories and other components.";
		$admtext['createtables'] = "Create Tables";
		$admtext['configsettings'] = "General Settings";
		$admtext['logconfigsettings'] = "Log Settings";
		$admtext['importconfigsettings'] = "Import Settings";
		$admtext['diagnostics'] = "Diagnostics";
		$admtext['rundiags'] = "Run Diagnostics";
		$admtext['phpinf'] = "PHP Info Screen";
		$admtext['fromphp'] = "This information comes from your server and relates to your PHP installation, not TNG.";
		$admtext['phpver'] = "PHP version";
		$admtext['phpreq'] = "(TNG requires 4.0.4 or higher.)";
		$admtext['gdlib'] = "GD graphics library";
		$admtext['gdreq'] = "(Required for TNG's thumbnail creation tools.)";
		$admtext['availnogif'] = "Available, but does not support .gif images";
		$admtext['notinst'] = "Not installed";
		$admtext['safemode'] = "Safe Mode";
		$admtext['off'] = "Off";
		$admtext['on'] = "On";
		$admtext['fileuploads'] = "File Uploads";
		$admtext['fureq'] = "(Required for web-based GEDCOM upload, image upload and other form functionality.)";
		$admtext['perm'] = "Permitted";
		$admtext['notperm'] = "Not permitted, use FTP instead";
		$admtext['sqlver'] = "MySQL version";
		$admtext['sqlreq'] = "(TNG requires 4.0.1 or higher.)";
		$admtext['wsrvr'] = "Webserver";
		$admtext['fperms'] = "File/Folder Permissions";
		$admtext['fpreq'] = "(TNG requires some files and folders to have special access rights.)";
		$admtext['scruser'] = "Script running as user:";
		$admtext['phpuser'] = "PHP reports it as user:";
		$admtext['usrprob'] = "You may not have the necessary level of file access to run TNG without problems if you use both FTP and the TNG admin functions to manage files.";
		$admtext['rofile'] = "File is read-only:";
		$admtext['rofolder'] = "Folder is read-only:";
		$admtext['publog'] = "Public log";
		$admtext['admlog'] = "Admin log";
		$admtext['folderdne'] = "Folder does not exist:";
		$admtext['keyrw'] = "Key folders are all read/write";
		$admtext['cfgrw'] = "Configuration files are all read/write";
		$admtext['acceptable'] = "Acceptable.";
		$admtext['restricted'] = "Some functionality may be restricted. You may encounter errors during installation or while running TNG.";
		$admtext['needchngs'] = "TNG may not run without changes to your PHP or server configuration.";
		$admtext['yourbrowser'] = "Your browser:";
		$admtext['modifysettings'] = "Modify Configuration Settings";
		$admtext['dbhost'] = "Database Host";
		$admtext['dbname'] = "Database Name";
		$admtext['dbusername'] = "Database User Name";
		$admtext['dbpassword'] = "Database Password";
		$admtext['rootpath'] = "Root Path";
		$admtext['homepage'] = "Home Page";
		$admtext['emailaddress'] = "E-mail Address";
		$admtext['siteowner'] = "Site Owner";
		$admtext['maxdescgens'] = "Max Descendancy Generations";
		$admtext['disallow'] = "Disallow";
		$admtext['defaultallowed'] = "Default: Allowed";
		$admtext['maxsearchresults'] = "Max Search Results";
		$admtext['targetframe'] = "Target Frame";
		$admtext['table'] = "Table";
		$admtext['lastbackup'] = "Last Backup";
		$admtext['backup'] = "Back up";
		$admtext['restore'] = "Restore";
		$admtext['backupfilesize'] = "File Size";
		$admtext['succbackedup'] = "successfully backed up";
		$admtext['succrestored'] = "successfully restored";
		$admtext['change_cutoff'] = "'What's New' Days";
		$admtext['change_limit'] = "'What's New' Limit";
		$admtext['photosext'] = "Photos Extension";
		$admtext['defaulttree'] = "Default Tree";
		$admtext['requirelogin'] = "Require Login";
		$admtext['defaultdontrequire'] = "Default: Don't Require";
		$admtext['ldsdefault'] = "Show LDS Data";
		$admtext['ldson'] = "Always";
		$admtext['ldsoff'] = "Never";
		$admtext['ldspermit'] = "Depending on user rights";
		$admtext['allow'] = "Allow";
		$admtext['chooselang'] = "Dynamic Language Change";
		$admtext['optimize'] = "Optimize";
		$admtext['succoptimized'] = "successfully optimized";
		$admtext['customheader'] = "Custom Header";
		$admtext['customfooter'] = "Custom Footer";
		$admtext['custommeta'] = "Custom Meta";
		$admtext['lineending'] = "Line Ending";
		$admtext['backuppath'] = "Backup Folder";
		$admtext['photopath'] = "Photo Folder";
		$admtext['headstonepath'] = "Headstone Folder";
		$admtext['historypath'] = "History Folder";
		$admtext['backuprestoretables'] = "Back up, Restore &amp; Optimize Table Data";
		$admtext['shownames'] = "Show Names for Living";
		$admtext['initials'] = "Abbreviate first name";
		$admtext['regformat'] = "Register Format";
		$admtext['stdformat'] = "Standard Format";
		$admtext['thumbprefix'] = "Thumbnails Prefix";
		$admtext['thumbmaxh'] = "Thumbnail Max Height";
		$admtext['thumbmaxw'] = "Thumbnail Max Width";
		$admtext['thumbsuffix'] = "Thumbnails Suffix";
		$admtext['showextended'] = "Show Extended Photo Info";
		$admtext['shownotes'] = "Show Notes";
		$admtext['notestogether'] = "Underneath corresponding events where possible";
		$admtext['notesapart'] = "In Notes section";
		$admtext['lnprefixes'] = "Surname Prefixes (i.e., van, de)";
		$admtext['lntogether'] = "Keep as part of regular surname";
		$admtext['lnapart'] = "Treat as separate entity";
		$admtext['detectpfx'] = "Prefix Detection on Import";
		$admtext['lnpfxnum'] = "Num. prefixes each  (max)";
		$admtext['specpfx'] = "OR These specific prefixes";
		$admtext['newmedialinks'] = "New links for Photos/Histories";
		$admtext['maxgedcom'] = "Max Generations, GEDCOM download";
		$admtext['placestable'] = "Places Table";
		//$admtext['hslinkstable'] = "Headstone Links Table";
		$admtext['tngdomain'] = "Genealogy URL";
		$admtext['charset'] = "Character Set";
		$admtext['time_offset'] = "Server time offset (hours)";
		$admtext['backupall'] = "Back up Selected";
		$admtext['optimizeall'] = "Optimize Selected";
		$admtext['alltables'] = "Selected Tables";
		$admtext['brinstructions'] = "To back up, restore or optimize a table, click on the appropriate action icon for that table, or select multiple tables and apply that action to all selected by choosing the corresponding action at the top of the screen.";
		$admtext['tabstyle'] = "Tabs Style Sheet";
		$admtext['iconloc'] = "Menu Location";
		$admtext['topleft'] = "Top left, over heading";
		$admtext['topright'] = "Top right, next to heading";
		$admtext['indstart'] = "Individuals start with";
		$admtext['persinfo'] = "Personal information only";
		$admtext['allinfo'] = "All information";
		$admtext['thumbcols'] = "Columns in Thumbnail View";
		$admtext['stdesc'] = "Start Descendancy";
		$admtext['stexpand'] = "Expanded";
		$admtext['stcollapse'] = "Collapsed";
		$admtext['regnotes'] = "Show Notes on Register";
		$admtext['regnosp'] = "Register Generations";
		$admtext['chshow'] = "Always show everyone";
		$admtext['chifsp'] = "Remove individuals with no family";
		$admtext['restoreall'] = "Restore Selected";
		$admtext['surerestore'] = "Are you sure you want to restore the selected tables?";
		$admtext['surerestorets'] = "Are you sure you want to restore the table structure? All existing data will be lost!";
		$admtext['backupstruct'] = "Back up Table Structure";
		$admtext['tablestruct'] = "Table structure";
		$admtext['brinstructions2'] = "To back up or restore the table structure, click on the appropriate action icon below. WARNING: Restoring the table structure will delete all existing data!";
		$admtext['livedefault'] = "Show Living Data";
		$admtext['nodisplay'] = "Do not display";
		$admtext['menudisp'] = "Display menu";
		$admtext['asicons'] = "As icons";
		$admtext['asdrop'] = "As dropdown list";
		$admtext['gendex'] = "GENDEX Folder";
		$admtext['modifypedsettings'] = "Modify Pedigree Configuration Settings";
		$admtext['leftindent'] = "Left Indent";
		$admtext['boxnamesize'] = "Box Name Size";
		$admtext['namesizeshift'] = "Name Size Shift";
		$admtext['boxdatessize'] = "Box Dates Size";
		$admtext['datessizeshift'] = "Dates Size Shift";
		$admtext['boxcolor'] = "Box Color";
		$admtext['colorshift'] = "Color Shift (%)";
		$admtext['emptycolor'] = "Empty Color";
		$admtext['bordercolor'] = "Border Color";
		$admtext['shadowcolor'] = "Shadow Color";
		$admtext['boxwidth'] = "Box Width (w/o popups)";
		$admtext['boxheight'] = "Box Height (w/o popups)";
		$admtext['boxalign'] = "Box Alignment (w/o popups)";
		$admtext['boxheightshift'] = "Box Height Shift (w/o popups)";
		$admtext['boxHsep'] = "Box Horizontal Separation";
		$admtext['boxVsep'] = "Box Vertical Separation";
		$admtext['shadowoffset'] = "Shadow Offset";
		$admtext['linewidth'] = "Line Width";
		$admtext['borderwidth'] = "Border Width";
		$admtext['popupcolor'] = "Popup Color";
		$admtext['popupinfosize'] = "Popup Info Size";
		$admtext['popupinfosizeshift'] = "Popup Info Size Shift";
		$admtext['popuptimer'] = "Popup Timer (ms)";
		$admtext['pedevent'] = "Popup Event";
		$admtext['puboxwidth'] = "Box Width (w/popups)";
		$admtext['puboxheight'] = "Box Height (w/popups)";
		$admtext['puboxalign'] = "Box Alignment (w/popups)";
		$admtext['puboxheightshift'] = "Box Height Shift (w/popups)";
		$admtext['popupspouses'] = "Popup Spouses";
		$admtext['popupkids'] = "Popup Children";
		$admtext['popupchartlinks'] = "Popup Chart Links";
		$admtext['inclphotos'] = "Include Photos";
		$admtext['overflow'] = "Overflow";
		$admtext['pedcompact'] = "Compact";
		$admtext['pedstandard'] = "Standard";
		$admtext['pedtextonly'] = "Text Only";
		$admtext['relchart'] = "Relationship Chart";
		$admtext['maxupgen'] = "Max Relationship Generations";
		$admtext['left'] = "Left";
		$admtext['right'] = "Right";
		$admtext['center'] = "Center";
		$admtext['mouseover'] = "Mouse Over";
		$admtext['mousedown'] = "Mouse Down";
		$admtext['ahnentafel'] = "Ahnentafel";
		$admtext['pedbox'] = "Box";
		$admtext['hideempty'] = "Hide Empty Boxes";
		$admtext['logfilename'] = "Log File Name";
		$admtext['maxloglines'] = "Max Log Lines";
		$admtext['modifylogsettings'] = "Modify Log Configuration Settings";
		$admtext['badhosts'] = "Exclude Host Names";
		$admtext['admin'] = "(Admin)";
		$admtext['text_public'] = "(Public)";
		$admtext['saveimportstate'] = "Save Import State";
		$admtext['allowresume'] = "Save to allow resume if import fails";
		$admtext['modifyimportsettings'] = "Modify Import Configuration Settings";
		$admtext['commas'] = "Separate multiple entries by commas";
		$admtext['embeddedmedia'] = "Embedded Media";
		$admtext['assignnames'] = "Allow TNG to assign names to embedded media";
		$admtext['localphotopath'] = "Local Photo Path(s)";
		$admtext['localdocpath'] = "Local History Path(s)";
		$admtext['nopathmatch'] = "If no local path match";
		$admtext['wholepath'] = "Import entire path";
		$admtext['justname'] = "Import file name only";
		$admtext['gedpath'] = "GEDCOM Folder (Import/Export)";
		$admtext['makefolder'] = "Make Folder";
		$admtext['blankchangedt'] = "If 'Change Date' is blank";
		$admtext['usetoday'] = "Use current date";
		$admtext['useblank'] = "Leave it as is";
		$admtext['nobirthdate'] = "If no birth date, assume";
		$admtext['persliving'] = "Person is living";
		$admtext['persdead'] = "Person is deceased";
		$admtext['nodeathdate'] = "If no death date, assume deceased<br />if older than";
		//changed in 6.0.0
		$admtext['pedconfigsettings'] = "Chart Settings";
		$admtext['usepopups'] = "Initial Display";
		$admtext['maxpedgens'] = "Max Generations";
		//added in 6.0.0
		$admtext['dbsection'] = "Database";
		$admtext['tablesection'] = "Table Names";
		$admtext['foldersection'] = "Paths and Folders";
		$admtext['sitesection'] = "Site Design and Definition";
		$admtext['privsection'] = "Privacy";
		$admtext['namesection'] = "Names";
		$admtext['descsection'] = "Descendancy";
		$admtext['miscsection'] = "Miscellaneous";
		$admtext['mediatable'] = "Media Table";
		$admtext['pedanddesc'] = "Common Elements";
		$admtext['descchart'] = "Descendancy Chart";
		$admtext['pedchart'] = "Pedigree Chart";
		$admtext['initgens'] = "Initial Generations";
		$admtext['mediapath'] = "Multimedia Folder";
		$admtext['documentpath'] = "Document Folder";
		$admtext['localdocumentpath'] = "Local Document Path(s)";
		$admtext['localotherpath'] = "Local Path(s) for Other Media";
		$admtext['imgmaxh'] = "Image Max Height";
		$admtext['imgmaxw'] = "Image Max Width";
		$admtext['succdel'] = "successfully deleted";
		$admtext['delbkups'] = "Delete Selected Backups";
		$admtext['suredelbk'] = "Are you sure you want to delete the selected backups?";
		$admtext['showhome'] = "Show Home Link";
		$admtext['showsearch'] = "Show Search Link";
		$admtext['showlogin'] = "Show Login/Logout Link";
		$admtext['showprint'] = "Show Print Link";
		$admtext['showbmarks'] = "Show Add Bookmark Link";
		$admtext['server'] = "(server)";
		$admtext['client'] = "(client)";
		$admtext['sitename'] = "Site Name";
		$admtext['site_desc'] = "Site Description";
		$admtext['privnote'] = "Prefix for private notes";
		$admtext['custvars'] = "Note: You may create your own custom settings in \"customconfig.php\" (open in a text editor and follow the instructions).";
		$admtext['blockemail'] = "Block suggestions or new user registrations where";
		$admtext['addrcontains'] = "Address contains";
		$admtext['msgcontains'] = "Message contains";
		//added in 6.1.0
		$admtext['reqloginset'] = "\"Require Login\" must be set to Yes to enable this option";
		$admtext['treerestrict'] = "Restrict access to assigned tree";
		$admtext['mapconfigsettings'] = "Map Settings";
		$admtext['modifymapsettings'] = "Modify Map Configuration Settings";
		$admtext['mapkey'] = "Map Key";
		$admtext['maptype'] = "Map Type";
		$admtext['mapnormal'] = "Normal";
		$admtext['maphybrid'] = "Hybrid";
		$admtext['mapsatellite'] = "Satellite";
		$admtext['mapdimsind'] = "Dimensions, Individual Page";
		$admtext['mapdimshst'] = "Dimensions, Headstones Pages";
		$admtext['mapdimsadm'] = "Dimensions, Admin Pages";
		$admtext['mapwidth'] = "Width (% or px)";
		$admtext['mapheight'] = "Height (px)";
		$admtext['mapstlat'] = "Starting Latitude";
		$admtext['mapstlong'] = "Starting Longitude";
		$admtext['startoff'] = "Hide Admin Maps to Start";
		$admtext['conslpins'] = "Consolidate Duplicate Pins";
		$admtext['ssenabled'] = "Enable Slide Show";
		$admtext['ssrepeat'] = "Slide Show Auto Repeat";
		//changed in 7.0.0
		$admtext['sysinfo'] = "Information about your web site environment.";
		$admtext['albumlinkstable'] = "Album Media";
		$admtext['addresstable'] = "Addresses";
		$admtext['statestable'] = "States";
		$admtext['countriestable'] = "Countries";
		$admtext['notelinkstable'] = "Note Links";
		$admtext['medialinkstable'] = "Media Links";
		$admtext['saveimporttable'] = "Save Import";
		$admtext['brlinkstable'] = "Branch Links";
		$admtext['temptable'] = "Temp Events";
		$admtext['tleventstable'] = "Timeline Events";
		//added in 7.0.0
		$admtext['album2entitiestable'] = "Album Links";
		$admtext['doctype'] = "Doctype Declaration";
		$admtext['cemrows'] = "Max lines per column (approx.)";
		$admtext['cemblanks'] = "Suppress \"Unknown\" categories";
		$admtext['success'] = "Success";
		$admtext['fexists'] = "Failed. Folder already exists.";
		$admtext['fmanual'] = "Failed. Please create using an FTP program or online file manager.";
		$admtext['maintmode'] = "Maintenance Mode";
		$admtext['maintexp'] = "All database access is temporarily unavailable for site maintenance. Please try again later. If regular functions do not resume within a few hours of first seeing this message, please contact the site administrator.";
		$admtext['defimpopt'] = "Default Replace Option";
		$admtext['seltable'] = "Please select at least one table.";
		$admtext['renumber'] = "Resequence IDs";
		$admtext['idtype'] = "ID Type";
		$admtext['mindigits'] = "Minimum Digits";
		$admtext['niprefix'] = "Not including ID prefix";
		$admtext['finreseq'] = "Finished resequencing";
		$admtext['recsreseq'] = "records resequenced";
		$admtext['needmaint'] = "You must be in Maintenance Mode to run this utility (go to Setup &gt;&gt; Configuration &gt;&gt; General Settings)";
		$admtext['reseqwarn'] = "<strong>WARNING:</strong> Resequencing your IDs could cause external links to your site to break or point to erroneous locations.";
		$admtext['subroot'] = "Config Path";
		$admtext['srexpl'] = "Optional. If used, move the following files to the Config Path <strong>immediately</strong> after saving and make them writeable (664 permissions): config.php, customconfig.php, importconfig.php, logconfig.php, mapconfig.php, pedconfig.php.";
		$admtext['hidechr'] = "Hide Christening Labels";
		$admtext['datefmt'] = "Numeric Date Preference";
		$admtext['dayfirst'] = "Day/Month/Year";
		$admtext['monthfirst'] = "Month/Day/Year";
		$admtext['exusers'] = "Exclude Usernames";
		$admtext['mapstzm'] = "Default Zoom";
		$admtext['allowreg'] = "Allow new user registrations";
		$admtext['localhspath'] = "Local Headstone Path(s)";
		//added in 7.0.1
		$admtext['pardata'] = "Parental data on person page";
		$admtext['pnoevents'] = "Don't show any events";
		$admtext['pstdonly'] = "Show only standard family events";
		$admtext['palldata'] = "Show all events and media";
		$admtext['servertime'] = "Server time is";
		$admtext['sitetime'] = "and site time is";
		break;

	//findpersonform.php
	case "findpersonform":
		$admtext['enternamepart'] = "enter part of first and/or last name";
		$admtext['pleasenamepart'] = "Please enter a portion of a first or last name.";
		//added in 6.0.0
		$admtext['enternamepart2'] = "enter ID or part of first and/or last name";
		break;

	//findplace.php, findplaceform.php
	case "findplace":
		$admtext['pleaseplacepart'] = "Please enter part of a place name.";
		$admtext['addnewplace'] = "Add New Place";
		$admtext['createplace'] = "Create a record for a new place";
		$admtext['modifyplace'] = "Edit Existing Place";
		$admtext['editexistingplaceinfo'] = "Edit information for a previously entered place";
		$admtext['enterplace'] = "Please enter a place.";
		$admtext['newplaceinfo'] = "New Place Information";
		$admtext['existingplaceinfo'] = "Existing Information for Place";
		$admtext['changestoplace'] = "Changes to place";
		$admtext['selectplaceaction'] = "Select Place and Action";
		$admtext['mergeplaces'] = "Merge Places";
		$admtext['findmerge'] = "Find Merge Candidates";
		$admtext['selectplacemerge'] = "Select Places to Merge";
		$admtext['mcol1'] = "Merge<br/>these<br/>(delete)";
		$admtext['mcol2'] = "into<br/>this<br/>(keep)";
		$admtext['pmsucc'] = "Place merge successful";
		$admtext['nomerge'] = "Nothing to merge";
		$admtext['enterkeep'] = "Please select a merge target.";
		$admtext['backmerge'] = "Search again";
		$admtext['confdeleteplace'] = "Are you sure you want to delete this place?";
		//changed in 6.0.0
		$admtext['propagate'] = "Make changes to place name in existing events";
		break;
		
	//generateID.php
	case "generateID":
		$admtext['generatenewid'] = "Generate New ID";
		$admtext['generating'] = "Generating...Please wait";
		break;
	
	//secondary.php
	case "secondary":
		$admtext['trackinglines'] = "Tracking Lines of Descent...";
		$admtext['finishedtracking'] = "Finished tracking lines of descent.";
		$admtext['backtosecondary'] = "Back to Secondary Processes";
		$admtext['sortchildren'] = "Sort Children";
		$admtext['sortingchildren'] = "Sorting Children";
		$admtext['sortspouses'] = "Sort Spouses";
		$admtext['sortingspouses'] = "Sorting Spouses";
		$admtext['relabelbranches'] = "Relabel Branches";
		$admtext['relabeling'] = "Relabeling Branches";
		$admtext['creatinggendex'] = "Creating GENDEX file...";
		$admtext['finishedgendex'] = "Finished with GENDEX file creation.";
		//added in 7.0.0
		$admtext['tngnet'] = "Post your GENDEX file on the TNG Network";
		break;

	//newlanguage.php
	case "language":
		$admtext['addnewlanguage'] = "Add New Language";
		$admtext['enterlangdisplay'] = "Please enter a language display name.";
		$admtext['enterlangfolder'] = "Please enter the name of the folder where files for this language will be stored.";
		$admtext['newlanguageinfo'] = "New Language Information";
		$admtext['langdisplay'] = "Name for this language<br/>as it will be displayed for visitors";
		$admtext['langfolder'] = "Folder where language files<br/>will be stored";
		$admtext['createlanguage'] = "Create a record for a new language";
		$admtext['nolanguages'] = "No language records exist";
		$admtext['conflangdelete'] = "Are you sure you want to delete this language?";
		$admtext['existinglanguages'] = "Existing Language Information";
		$admtext['modifylanguage'] = "Edit Existing Language";
		$admtext['languagemenu'] = "Languages Menu";
		$admtext['changestolanguage'] = "Changes to language";
		$admtext['charset'] = "Character set";
		//changed in 6.0.0
		$admtext['editexistinglanguage'] = "Add, edit or delete languages";
		break;
	
	//addtree.php, trees.php, edittree.php, deletetree.php, newtree.php, updatetree.php
	case "trees":
		$admtext['createtree'] = "Create a record for a new tree";
		$admtext['notrees'] = "No tree records exist";
		$admtext['existingtrees'] = "Existing Tree Information";
		$admtext['editexistingtree'] = "Edit information for a previously entered tree";
		$admtext['treename'] = "Tree Name";
		$admtext['owner'] = "Owner";
		$admtext['conftreedelete'] = "Are you sure you want to delete this tree and all associated items?";
		$admtext['conftreeclear'] = "Are you sure you want to clear all data from this tree?";
		$admtext['changestotree'] = "Changes to tree";
		$admtext['newtreeinfo'] = "New Tree Information";
		$admtext['existingtreeinfo'] = "Existing Tree Information";
		$admtext['modifytree'] = "Edit Existing Tree";
		$admtext['succcleared'] = "was successfully cleared";
		$admtext['treemenu'] = "Trees Menu";
		$admtext['gedcomextraction'] = "Don't allow users to download GEDCOM files";
		$admtext['gedexport'] = "GEDCOM Export";
		$admtext['exporting'] = "Exporting GEDCOM...";
		$admtext['ifexportfails'] = "If the export fails to run to completion,";
		$admtext['resume'] = "click here to resume";
		$admtext['finishedexporting'] = "Finished Exporting GEDCOM";
		$admtext['backtotrees'] = "Back to Trees";
		$admtext['downloadged'] = "Download GEDCOM";

		$admtext['lastimport'] = "Last Import";
		$admtext['text_private'] = "Keep owner information private";
		$admtext['treeexists'] = "Another tree already exists with the selected ID. Please select a different ID and try again.";
		//changed in 6.0.0
		$admtext['exportmedia'] = "Export media links";
		//added in 6.0.0
		$admtext['exppaths'] = "Local paths for";
		break;

	//adduser.php, users.php, edituser.php, deleteuser.php, newuser.php, updateuser.php
	case "users":
		$admtext['addnewuser'] = "Add New User";
		$admtext['createuser'] = "Create a record for a new user";
		$admtext['nousers'] = "No user records exist";
		$admtext['existingusers'] = "Existing User Information";
		$admtext['editexistinguser'] = "Edit information for a previously entered user";
		$admtext['confuserdelete'] = "Are you sure you want to delete this user?";
		$admtext['changestouser'] = "Changes to user";
		$admtext['enteruserpassword'] = "Please enter a password.";
		$admtext['enterusername'] = "Please enter a username.";
		$admtext['newuserinfo'] = "New User Information";
		$admtext['existinguserinfo'] = "Existing User Information";
		$admtext['modifyuser'] = "Edit Existing User";
		$admtext['usermenu'] = "Users Menu";
		$admtext['allow_edit'] = "Allow to edit existing records";
		$admtext['allow_add'] = "Allow to add new records";
		$admtext['allow_delete'] = "Allow to delete existing records";
		$admtext['allow_living'] = "Allow to view information for living individuals";
		$admtext['allow_lds'] = "Allow to view LDS information";
		$admtext['enterusername'] = "Please enter a username.";
		$admtext['enteruserdesc'] = "Please enter a user description.";
		$admtext['enterpassword'] = "Please enter a password.";
		$admtext['admin'] = "Admin";
		$admtext['firstuser'] = "The first user you create will be an Administrator (NO tree selected) and will have access to all system settings.";
		$admtext['userfailed'] = "ERROR: Your user could not be created because another user with the same username already exists.";
		$admtext['allow_ged'] = "Allow to download GEDCOMs";
		$admtext['assigned'] = "Assigned";
		$admtext['treemsg'] = "Optional. Assigning no tree to the user will result in the user have rights for all trees and all branches. The site administrator should not be assigned a tree.";
		$admtext['branchmsg'] = "Optional. Assigning a branch to the user will constrain the rights granted on this page to the assigned branch within the selected tree.";
		$admtext['accesslimits'] = "Access Limits:";
		$admtext['rights'] = "Rights:";
		$admtext['realname'] = "Real Name";
		$admtext['gedcom'] = "GEDCOM";
		$admtext['newusers'] = "New User Registrations";
		$admtext['editnewusers'] = "Process records for newly registered users. New users have no rights until registrations are processed.";
		$admtext['nonewusers'] = "No new users";
		$admtext['lastlogin'] = "Last Login";
		$admtext['tentative_edit'] = "Allow to submit edits for administrative review (People, Families and Sources only)";
		$admtext['notify'] = "Notify this user upon account activation";
		$admtext['hello'] = "Hello";
		$admtext['activated'] = "Your genealogy user account has been activated.";
		$admtext['infois'] = "Your login information is";
		//added in 6.0.0
		$admtext['no_edit'] = "No edit rights";
		$admtext['emailusers'] = "E-mail Users";
		//$admtext['sendemailstousers'] = "Send an e-mail to all registered users";
		$admtext['emailmessage'] = "E-mail Message To Users";
		$admtext['subject'] = "E-mail Subject";
		$admtext['messagetext'] = "E-mail Text";
		$admtext['selectgroup'] = "Select group to receive e-mail (leave blank to send to all)";
		$admtext['treemailmsg'] = "Optional. Choosing a tree will restrict the message to users assigned to that tree.";
		$admtext['branchmailmsg'] = "Optional. Choosing a branch will restrict the message to users assigned to that branch.";
		$admtext['send'] = "Send E-mail";
		$admtext['sentmailmessage'] = "Sent E-mail Message";
		$admtext['succmail'] = "Your e-mail message has been sent.";
		$admtext['mailfailed'] = "Your e-mail message failed to send.";
		$admtext['entersubject'] = "Please enter a subject for your message.";
		$admtext['entermsgtext'] = "Please enter the text of your message.";
		$admtext['adminonly'] = "Show Admin users only";
		$admtext['dtregistered'] = "Date Registered";
		$admtext['dtactivated'] = "Date Activated";
		$admtext['no_email'] = "Do not send mass e-mail to this user";
		//changed in 7.0.0
		$admtext['allow_admin'] = "Allow access to all system settings and administrative functions, and apply the above rights to all trees and branches.";
		$admtext['limitedrights'] = "Restrict the above rights to the following:";
		break;

	case "login":
		$admtext['loginfailed'] = "Login failed.";
		$admtext['adminlogfile'] = "Admin Log File";
		$admtext['mostrecentactions'] = "Most Recent Actions";
		$admtext['rempass'] = "Stay logged in on this computer";
		$admtext['sessexp'] = "Your session has expired.";
		$admtext['logagain'] = "Click to log in again.";
		break;

	//added in 5.0.0
	case "timeline":
		$admtext['createnewtlevent'] = "Create a new timeline event";
		$admtext['modifytlevent'] = "Edit Existing Timeline Event";
		$admtext['leaveblankalltlevents'] = "leave blank to show all timeline events";
		$admtext['evyear'] = "Event year";
		$admtext['evdetail'] = "Event detail";
		$admtext['selecttleventaction'] = "Select Timeline Event and Action";
		$admtext['changestotlevent'] = "Changes to timeline event";
		$admtext['location'] = "Location";
		$admtext['confdeletetlevent'] = "Are you sure you want to delete this timeline event?";
		$admtext['enterevyear'] = "Please enter the event year.";
		$admtext['enterevdetail'] = "Please enter the event detail.";
		$admtext['existingtleventinfo'] = "Existing Timeline Event";
		$admtext['newtleventinfo'] = "New Timeline Event";
		//changed in 6.0.0
		$admtext['edittleventinfo'] = "Add, edit or delete timeline events";
		$admtext['addnewtlevent'] = "Add New Event";
		//added in 6.0.0
		$admtext['yrreq'] = "(only year is required)";
		break;

	case "review":
		$admtext['selectevaction'] = "Select Event and Action";
		$admtext['suggested'] = "Suggested";
		$admtext['usernotes'] = "Notes regarding<br />suggested change<br />(will not be saved)";
		$admtext['postdate'] = "Posted on";
		$admtext['savedel'] = "Save and Delete";
		$admtext['postpone'] = "Postpone";
		$admtext['igndel'] = "Ignore and Delete";
		$admtext['tentdata'] = "Temporary event record";
		//added in 6.0.0
		$admtext['tentdel'] = "was deleted";
		$admtext['tentadd'] = "was made permanent";
		//changed in 7.0.0
		$admtext['tentdata'] = "Temporary event record for ";
		break;
}

//common
$admtext['cannotexecutequery'] = "Cannot execute query";
$admtext['addnew'] = "Add New";
$admtext['idexists'] = "could not be added because this ID already exists. Please return to the previous page and select a different ID.";
$admtext['individuals'] = "individuals";
$admtext['succadded'] = "was successfully added";
$admtext['succaddedlinked'] = "was successfully added and linked to";
$admtext['succsaved'] = "were successfully saved";
$admtext['succdeleted'] = "was successfully deleted";
$admtext['succdeletedpluslinks'] = "was successfully deleted, along with all links";
$admtext['text_delete'] = "Delete";
$admtext['deleted'] = "Deleted";
$admtext['deleteselected'] = "Delete Selected";
$admtext['noresults'] = "No results found. Please try again.";
$admtext['adminmenu'] = "Administration Menu";
$admtext['action'] = "Action";
$admtext['id'] = "ID";
$admtext['edit'] = "Edit";
$admtext['notes'] = "Notes";
$admtext['name'] = "Name";
$admtext['description'] = "Description";
$admtext['text_continue'] = "Continue...";
$admtext['searchfor'] = "Search for";
$admtext['lookin'] = "Look in (check all that apply)";
$admtext['cemeteryid'] = "Cemetery ID";
$admtext['exactmatch'] = "Exact match only";
$admtext['nothingtodelete'] = "Nothing to delete";
$admtext['state'] = "state";
$admtext['country'] = "country";
$admtext['finish'] = "Finish";
$admtext['ifphotouploaded'] = "Leave this field blank if the file has already been uploaded to your photos folder.";
$admtext['eventtype'] = "Event Type";
$admtext['source'] = "Source";
$admtext['savechanges'] = "Save Changes";
$admtext['family'] = "Family";
$admtext['find'] = "Find...";
$admtext['create'] = "Create...";
$admtext['sourceid'] = "Source ID";
$admtext['birthabbr'] = "b.";
$admtext['chrabbr'] = "c.";
$admtext['remove'] = "Remove";
$admtext['moveup'] = "Move Up";
$admtext['movedown'] = "Move Down";
$admtext['enterpersonid'] = "Please enter a Person ID";
$admtext['personid'] = "Person ID";
$admtext['otherevents'] = "Other Events";
$admtext['required'] = "required";
$admtext['children'] = "Children";
$admtext['yes'] = "Yes";
$admtext['no'] = "No";
$admtext['chrdate'] = "Christening Date";
$admtext['chrplace'] = "Christening Place";
$admtext['deathdate'] = "Death Date";
$admtext['deathplace'] = "Death Place";
$admtext['burialdate'] = "Burial Date";
$admtext['burialplace'] = "Burial Place";
$admtext['birthdate'] = "Birth Date";
$admtext['birthplace'] = "Birth Place";
$admtext['title'] = "Title";
$admtext['sex'] = "Gender";
$admtext['marriagedate'] = "Marriage Date";
$admtext['marriageplace'] = "Marriage Place";
$admtext['lastname'] = "Last Name";
$admtext['firstname'] = "First Name";
$admtext['filename'] = "File Name";
$admtext['linkspersonid'] = "Links (Person ID)";
$admtext['cannotopen'] = "Cannot open file";
$admtext['check'] = "Check";
$admtext['generate'] = "Generate";
$admtext['update'] = "Update";
$admtext['setupmenu'] = "Setup Menu";
$admtext['confdeleteevent'] = "Are you sure you want to delete this event?";
$admtext['existinglinks'] = "Existing Links:<br/>(check to delete)";
$admtext['lowersortfirst'] = "Lower numbers sort first. Decimal numbers may also be used.";
$admtext['personsname'] = "Person's Name";
$admtext['tablecreation'] = "Table Creation";
//$admtext['creategendex'] = "Create GENDEX";
$admtext['tracklines'] = "Track Lines";
$admtext['administration'] = "Administration";
$admtext['text_or'] = "OR";
$admtext['cemeteries'] = "Cemeteries";
$admtext['families'] = "Families";
$admtext['headstones'] = "Headstones";
$admtext['histories'] = "Histories";
$admtext['people'] = "People";
$admtext['photos'] = "Photos";
$admtext['reports'] = "Reports";
$admtext['sources'] = "Sources";
$admtext['suffix'] = "Suffix";
$admtext['add'] = "Add";
$admtext['confdeleteentity'] = "Are you sure you want to delete the selected";
$admtext['cemetery'] = "Cemetery";
$admtext['language'] = "Language";
$admtext['display'] = "Display";
$admtext['languages'] = "Languages";
$admtext['orderpound'] = "Order #";
$admtext['tree'] = "Tree";
$admtext['alltrees'] = "All Trees";
$admtext['selectaddtree'] = "Tree (select or add new)";
$admtext['selecttree'] = "Please select/add a tree.";
$admtext['treebefevent'] = "You must select or enter a Tree name before you can add new events.";
$admtext['text_rename'] = "Rename";
$admtext['clear'] = "Clear";
$admtext['linktothis'] = "Link to this individual";
$admtext['linkexample'] = "(enter ID, i.e. \"I###\")";
$admtext['existingconfig'] = "Existing Configuration";
$admtext['lastmodified'] = "Last Modified";
$admtext['addnotes'] = "Additional Notes";
$admtext['confdeletenote'] = "Are you sure you want to delete this note?";
$admtext['treebefnote'] = "You must select or enter a Tree name before you can add new notes.";
$admtext['BIRT'] = "Birth";
$admtext['DEAT'] = "Death";
$admtext['CHR'] = "Christening";
$admtext['BURI'] = "Burial";
$admtext['BAPL'] = "Baptism (LDS)";
$admtext['ENDL'] = "Endowment (LDS)";
$admtext['NICK'] = "Nickname";
$admtext['TITL'] = "Title";
$admtext['NSFX'] = "Suffix";
$admtext['NAME'] = "Name";
$admtext['SLGC'] = "Sealed to Parents (LDS)";
$admtext['MARR'] = "Married";
$admtext['SLGS'] = "Sealed to Spouse (LDS)";
$admtext['general'] = "General";
$admtext['entersearchvalue'] = "Please enter a search value.";
$admtext['trees'] = "Trees";
$admtext['users'] = "Users";
$admtext['living'] = "Living";
$admtext['lds'] = "LDS";
$admtext['norights'] = "You are not authorized to view this page. If you have a username and password, please login below.";
$admtext['username'] = "Username";
$admtext['password'] = "Password";
$admtext['login'] = "Login";
$admtext['logout'] = "Logout";
$admtext['city'] = "City";  //from cemeteries
$admtext['cap_country'] = "Country";  //from cemeteries
$admtext['addnewtree'] = "Add New Tree";
$admtext['test'] = "Test";
$admtext['page'] = "Page";  //from sources
$admtext['folder'] = "Folder";   //from languages
$admtext['confdeletepers'] = "Are you sure you want to delete this person? The individual will be entirely deleted from your tree.";
$admtext['save'] = "Save";
$admtext['of'] = "of";
$admtext['size'] = "Size";
$admtext['select'] = "Select";
$admtext['open'] = "Open";
$admtext['selectfile'] = "Select File";
$admtext['altdesc'] = "Alternate Description";
$admtext['altnotes'] = "Alternate Notes";
$admtext['savereturn'] = "Return to this page";
$admtext['saveback'] = "Return to menu";
$admtext['user'] = "User";
$admtext['DIV'] = "Divorced";
$admtext['search'] = "Search";  //from findpersonform
$admtext['searchresults'] = "Search Results";  //from people
$admtext['clicktoselect'] = "click to select";
$admtext['familyid'] = "Family ID";  //from families
$admtext['secondary'] = "Secondary Processes";
$admtext['commas'] = "Separate multiple entries with commas";
$admtext['onsave'] = "On save";
$admtext['adminhome'] = "Admin Home";
$admtext['labelbranches'] = "Label Branches";
$admtext['branch'] = "Branch";
$admtext['datenote'] = "<strong>Note:</strong> When entering dates, please use the standard genealogical format DD MMM YYYY.<br />For example, 10 Apr 2004.";
$admtext['findperson'] = "Find Person...";
$admtext['findfamily'] = "Find Family...";
$admtext['repeatlastq'] = "Repeat last search";
$admtext['alwayson'] = "Always viewable";
$admtext['all'] = "All";
$admtext['lnprefix'] = "Surname Prefix";
$admtext['nameorder'] = "Name Order";
$admtext['western'] = "First name first";
$admtext['oriental'] = "Surname first";
$admtext['lockid'] = "Lock";
$admtext['linktothese'] = "Link to:";
$admtext['alsolinkto'] = "Also link to:";
$admtext['linkspersfam'] = "Links (Person, Family or Source ID)";
$admtext['findsource'] = "Find Source...";
$admtext['address'] = "Address";
$admtext['stateprov'] = "State/Province";
$admtext['zip'] = "Zip/Postal Code";
$admtext['merge'] = "Merge";
$admtext['otherinfo'] = "Other Information";
$admtext['available'] = "Available";
$admtext['backuprestore'] = "Utilities";
$admtext['place'] = "Place";
$admtext['treeid'] = "Tree ID";
$admtext['email'] = "E-mail";
$admtext['event'] = "Event";
$admtext['eventdate'] = "Event Date";
$admtext['eventplace'] = "Event Place";
$admtext['detail'] = "Detail";
$admtext['export'] = "Export";
$admtext['tlevents'] = "Timeline Events";
$admtext['places'] = "Places";
$admtext['duplicate'] = "Changes were not saved. Another record with the same key already exists.";
$admtext['alttitle'] = "Alternate Title";
$admtext['enttitle'] = "Title";  //title for a history or photo, not a person
$admtext['address1'] = "Address 1";
$admtext['address2'] = "Address 2";
$admtext['countryaddr'] = "Country";
$admtext['branches'] = "Branches";
$admtext['nobranch'] = "No Branch";
$admtext['scrollbranch'] = "(Scroll to see all choices)";
$admtext['matches'] = "Matches";
$admtext['review'] = "Review";
$admtext['allusers'] = "All Users";
$admtext['deathabbr'] = "d.";
$admtext['burialabbr'] = "bur.";
$admtext['nochanges'] = "No changes were made.";
$admtext['changestoallitems'] = "Changes to all items";  //were made successfully
$admtext['find2'] = "Find";
$admtext['text_sort'] = "Sort";
$admtext['documents'] = "Documents";
$admtext['repository'] = "Repository";
$admtext['more'] = "More";
$admtext['repositories'] = "Repositories";
$admtext['divplace'] = "Divorce Place";
$admtext['divdate'] = "Divorce Date";
$admtext['divdatetr'] = "Divorce Date (True)";
$admtext['creategendex'] = "Create GENDEX";
//changed in 6.0.0
$admtext['datamaint'] = "Import/Export";
$admtext['imagefiletoupload'] = "File to upload";
$admtext['indfamorsrc'] = "individual(s), families, sources, repositories or places.";
$admtext['improperpermissions'] = "because the folder does not exist (check the Root Path) or does not have proper permissions (try chmod(777)).";
//moved here in 6.0.0
$admtext['person'] = "Person";
$admtext['setup'] = "Setup";
$admtext['addnew'] = "Add New";
$admtext['manage'] = "Manage";
$admtext['reset'] = "Reset";
$admtext['norecords'] = "No records exist.";
$admtext['secondarymaint'] = "Secondary Processes";
$admtext['customeventtypes'] = "Custom Event Types";
$admtext['findmatches'] = "Find Matches";
$admtext['matchthese'] = "Match the following fields:";
$admtext['otheroptions'] = "Other Options:";
$admtext['ignoreblanks'] = "Ignore Blanks";
$admtext['nextmatch'] = "Next Match";
$admtext['nextdup'] = "Next Duplicate";
$admtext['comprefresh'] = "Compare/Refresh";
$admtext['mswitch'] = "Switch";
$admtext['nomatches'] = "No Matches";
$admtext['combineextras'] = "Combine media";  //changed as well
$admtext['fasterdisplay'] = "Note: This page is formatted differently to allow for faster display.";
$admtext['publichome'] = "Public Home";
$admtext['selectall'] = "Select All";
$admtext['clearall'] = "Clear All";
//added in 6.0.0
$admtext['media'] = "Media";
$admtext['albums'] = "Albums";
$admtext['import'] = "Import";
$admtext['item'] = "Item";
$admtext['combinenotesonly'] = "Combine notes";
$admtext['addmedia'] = "Add Media";
$admtext['latitude'] = "Latitude";
$admtext['longitude'] = "Longitude";
$admtext['gedimport'] = "GEDCOM Import";
$admtext['improper2'] = "because the original file is too large or is not a valid image, or because the folder does not exist (check the Root Path) or does not have proper permissions (try chmod(777)).";
//added in 6.0.4
$admtext['confdeleterecs'] = "Are you sure you want to delete the selected records?";
//added in 6.1.0
//For Google maps use - admin pages
$admtext['googleplace'] = "Geocode Location";
$admtext['notfound'] = " not found. Try another search. Check the Map Search Help for possible reasons the search failed, or try your search using the Full Google Map Search link";
$admtext['showhidemap'] = "Show/hide clickable map";
$admtext['getcoords'] = "(to determine latitude, longitude and zoom)";
$admtext['searchstring'] = "Search for a Place";
$admtext['zoom'] = "Zoom";
$admtext['selectplacelevel'] = "Select Place Level";
$admtext['difficultmap'] = "Full Google Map Search";
$admtext['maphelp'] = "Map Search Help";
$admtext['gobutton'] = "Search";
//moved here in 7.0.0
$admtext['findpersonid'] = "Find Person ID";
$admtext['findfamilyid'] = "Find Family ID";
$admtext['findsourceid'] = "Find Source ID";
$admtext['entersourcepart'] = "Enter part of source title";
$admtext['findrepoid'] = "Find Repository ID";
$admtext['enterrepopart'] = "Enter part of repository title";
$admtext['findplace'] = "Find Place";
$admtext['enterplacepart'] = "enter part of a place name";
$admtext['entereventinfo'] = "Please enter an Event Date, an Event Place or the Detail for this event.";
$admtext['entereventtype'] = "Please select an Event Type.";
$admtext['enternote'] = "Please enter the note text.";
$admtext['selectsource'] = "Please select a Source.";
$admtext['confdeletecite'] = "Are you sure you want to delete this citation?";
$admtext['spouses'] = "Spouses / Partners";
$admtext['entertreeid'] = "Please enter a tree ID.";
$admtext['entertreename'] = "Please enter a tree name.";
$admtext['citations'] = "Citations";
$admtext['eventtypes'] = "Event Types";
$admtext['associations'] = "Associations";
$admtext['makefolder'] = "Make Folder";
$admtext['allcurrentdata'] = "All current data";
$admtext['matchingonly'] = "Matching records only";
$admtext['donotreplace'] = "Do not replace any data";
$admtext['useroffset'] = "Start IDs at:";
$admtext['phone'] = "Phone";
$admtext['website'] = "Web Site";
$admtext['thumb'] = "Thumb";  //as in thumbnail
$admtext['displayorder'] = "Display Order";
$admtext['go'] = "Go";
//changed in 7.0.0
$admtext['help'] = "Help for this area";
$admtext['husband'] = "Father";
$admtext['wife'] = "Mother";
$admtext['husbname'] = "Father's Name";
$admtext['wifename'] = "Mother's Name";
//added in 7.0.0
$admtext['drag'] = "Drag";
$admtext['linktype'] = "Link Type";
$admtext['enterinamepart'] = "enter part of first and/or last name";
$admtext['enterfnamepart'] = "Enter part of father's and/or mother's name";
$admtext['hide'] = "Hide";
$admtext['toggle'] = "toggle display";
$admtext['wsel'] = "With selected:";
$admtext['msg'] = "Message";
$admtext['default'] = "Default";
$admtext['events'] = "Events";
$admtext['date'] = "Date";
$admtext['savecont'] = "Save and continue...";
$admtext['alphanum'] = "Please use only alphanumeric characters in your Tree ID.";
$admtext['mediatypes'] = "Media Types";
$admtext['appendall'] = "Append all records";
$admtext['NPFX'] = "Prefix";
$admtext['prefix'] = "Prefix";
$admtext['mostwanted'] = "Most Wanted";

global $rootpath;
if($rootpath) {
	$thislanguage = $mylanguage ? $mylanguage : $language;
	include_once($rootpath . $cms['tngpath'] . "$thislanguage/alltext.php");
}
else
	include_once("alltext.php");
?>